config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'sessions/create'

  get 'sessions/destroy'


devise_for :users
  
 #resources :users
 
  resources :halls do
  resources :fields 
  resources :comments
  end

  root 'halls#index'
   
  #Facebook Stuff
  #devise_scope :user do
 # delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
#end
  



end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :hall
  belongs_to :user
end

app/models/field.rb
class Field < ActiveRecord::Base
belongs_to :hall
end

app/models/hall.rb
class Hall < ActiveRecord::Base

 has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

belongs_to :user
has_many :fields
has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

        

         
has_many :halls
has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # helper_method :current_user

  
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
  end

  # GET /comments/1/edit
  def edit
    @hall = Hall.find(params[:hall_id])
@comment = @hall.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
     @hall = Hall.find(params[:hall_id])  
     @comment = @hall.comments.create(comment_params) 
     @comment.user_id = current_user.id 

    respond_to do |format|
      if @comment.save
        format.html {  redirect_to hall_path(@hall), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to hall_path(@hall = Hall.find(params[:hall_id])), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to hall_path(@hall = Hall.find(params[:hall_id])), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :hall_id, :user_id)
    end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]

  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    @hall = Hall.find(params[:hall_id])
    @field = @hall.fields.create(params[:field].permit(:title, :text))

    respond_to do |format|
      if @field.save
        format.html { redirect_to hall_path(@hall), notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
 @field.destroy
  redirect_to hall_path(@hall = Hall.find(params[:hall_id]))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:title, :text)
    end
end

app/controllers/halls_controller.rb
class HallsController < ApplicationController
  before_action :set_hall, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /halls
  # GET /halls.json
  def index
    @halls = Hall.all
  end

  # GET /halls/1
  # GET /halls/1.json
  def show
  end

  # GET /halls/new
  def new
    @hall = current_user.halls.build
  end

  # GET /halls/1/edit
  def edit
  end

  # POST /halls
  # POST /halls.json
  def create
    @hall = current_user.halls.build(hall_params)

    respond_to do |format|
      if @hall.save
        format.html { redirect_to @hall, notice: 'Hall was successfully created.' }
        format.json { render :show, status: :created, location: @hall }
      else
        format.html { render :new }
        format.json { render json: @hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /halls/1
  # PATCH/PUT /halls/1.json
  def update
    respond_to do |format|
      if @hall.update(hall_params)
        format.html { redirect_to @hall, notice: 'Hall was successfully updated.' }
        format.json { render :show, status: :ok, location: @hall }
      else
        format.html { render :edit }
        format.json { render json: @hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /halls/1
  # DELETE /halls/1.json
  def destroy
    @hall.destroy
    respond_to do |format|
      format.html { redirect_to halls_url, notice: 'Hall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_hall
      @hall = Hall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hall_params
      params.require(:hall).permit(:title, :text, :image)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/halls_helper.rb
module HallsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_comment.html.erb
<p><%=comment.content %></p>

<p>Posted by: <%=comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>


<% if user_signed_in? %>
<% if comment.user_id == current_user.id %>
<%= link_to "Edit", edit_hall_comment_path(comment.hall, comment) %>
<%= link_to "Delete", hall_comment_path(comment.hall, comment), method: :delete, data: {confirm: "Are you sure?"}%>
<%end%>
<%end%>

app/views/comments/_form.html.erb
<%= form_for([@hall, @hall.comments.build]) do |f| %>

<div class=“field”>


<%= f.text_area :content %>

</div>

<div class=“actions”>

<%= f.submit %>

</div>

<% end %>

app/views/comments/edit.html.erb
<div class="edit">
<h1>Editing Comment</h1>

<%= form_for([@hall, @comment]) do |f|%>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<div class="links">
<%= link_to 'Back', (hall_path (@hall)) %>
</div>
</div>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Hall</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.hall %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Hall:</strong>
  <%= @comment.hall %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/fields/_field.html.erb
              <h4 class="card-title">
               <strong> <span><%= field.title %></span></strong>
              </h4>
              <span class="card-text" ><%= field.text %></span>
   
            <div>
            <% if user_signed_in? %>
            <% if @hall.user_id == current_user.id %>
            <%= link_to "Delete", hall_field_path(@hall, field.id), method: :delete, data: { confirm: "Are you sure?" } %>
            <% end %>
            <% end %>
            </div>
            <br>
        




app/views/fields/_form.html.erb
<%= form_for([@hall, @hall.fields.build]) do |f| %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing Field</h1>

<%= render 'form' %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fields</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fields.each do |field| %>
      <tr>
        <td><%= field.title %></td>
        <td><%= field.text %></td>
        <td><%= link_to 'Show', field %></td>
        <td><%= link_to 'Edit', edit_field_path(field) %></td>
        <td><%= link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Field', new_field_path %>

app/views/fields/new.html.erb
<h1>New Field</h1>

<%= render 'form' %>

<%= link_to 'Back', fields_path %>

app/views/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @field.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @field.text %>
</p>

<%= link_to 'Edit', edit_field_path(@field) %> |
<%= link_to 'Back', fields_path %>

app/views/halls/_form.html.erb
<%= form_for @hall, { multipart: true } do |f| %>
  <% if @hall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hall.errors.count, "error") %> prohibited this hall from being saved:</h2>

      <ul>
      <% @hall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
   <%= f.label :image %><br>
   <%= f.file_field :image %>
 </div>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/halls/edit.html.erb
<h1>Editing Hall</h1>

<%= render 'form' %>

<%= link_to 'Show', @hall %> |
<%= link_to 'Back', halls_path %>

app/views/halls/index.html.erb
<div class="container">
<div class="row">
<p id="notice"><%= notice %></p>

 <% @halls.each do |hall| %>

        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <span><%= image_tag hall.image.url(:medium), :class => "imgg" %></span>
            <div class="card-body">
              <h4 class="card-title">
                <span class="textt"><%= link_to hall.title, hall_path(hall) %></span>
              </h4>
              <span><%= hall.text.first(100) %></span>
            </div>
          </div>
        </div>
               
<% end %>

 </div>
 </div>

app/views/halls/new.html.erb
<div class="container text-center">
<div class="col-lg-4 col-lg-offset-4">
<div class="border">

<h1>New Hall</h1>

<%= render 'form' %>

<%= link_to 'Back', halls_path %>

</div>
</div>
</div>

app/views/halls/show.html.erb
 <div class="container">
<p id="notice"><%= notice %></p>

<strong><p class="title_center">
  <!--<strong>Title:</strong>-->
  <%= @hall.title %>
</p></strong>

<p>
  <!--<strong>Text:</strong>-->
  <%= @hall.text %>
</p>

<h2> Fields </h2>
<br>

<div>
    <%= render @hall.fields %>
</div>


<h2> Add Fields </h2>
<% if user_signed_in? %> 
<% if @hall.user_id == current_user.id %>
<div>
    <%= render "fields/form" %> 
</div>

<% end %>
<% end %>
<br>
<p class="line"></p>
<div>
<h3> Comments </h3>
    <%= render @hall.comments%>
</div>



<div>
<h3> Post a comment! </h3>
<%= render 'comments/form' %>
</div>

<% if user_signed_in? %>
<% if @hall.user_id == current_user.id %>
<%= link_to 'Edit', edit_hall_path(@hall) %> |
<%= link_to 'Destroy', @hall, method: :delete, data: { confirm: 'Are you sure?' } %>
<%end%>
<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SportneDvorane</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<%= link_to "Sportne Dvorane", root_path, class: "navbar-brand" %>
			</div>
			<ul class="navbar-nav nav">
			<% if !user_signed_in? %>
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% end %>
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>	
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>
			</ul>
			<% if user_signed_in? %>
				<p><%= link_to "New Hall", new_hall_path, class: "navbar-text navbar-link navbar-right" %></p>
			<% end %>
		</div>
</nav>


<%=  yield %>

</body>
</html>